affinity_prediction:
  config_base: kns/pytorch_connectomics/configs/SNEMI/SNEMI-Base.yaml
  config_file: kns/pytorch_connectomics/configs/SNEMI/SNEMI-Affinity-UNet.yaml
  checkpoint: /gpfs/marilyn/pi/kuan/shared/FIB_SEM/WORM/pretrain_checkpoint/checkpoint_110000.pth.tar
  hpc: kns/pytorch_connectomics/configs/hpc.yaml
  split: kns/pytorch_connectomics/configs/config_split.yaml
  merge: kns/pytorch_connectomics/configs/config_merge.yaml
instance_segmentation:
  main: kns/instance_segmentation/configs/config.yaml
  prec: kns/instance_segmentation/configs/config_prec.yaml
  downsample: kns/instance_segmentation/configs/config_downsample.yaml
  gen_mask: kns/instance_segmentation/configs/config_gen_mask.yaml
  mask_prec: kns/instance_segmentation/configs/config_mask.yaml
  mask_tif: kns/instance_segmentation/configs/config_mask_tif.yaml
  resize_tif: kns/instance_segmentation/configs/config_resize_tif.yaml
