paths:
  input: "/gpfs/marilyn/pi/kuan/shared/ET/UCSD_11k_tomos/tif/MouseCerebellum_A3S1_SA11k_de64_tomo17/MouseCerebellum_A3S1_SA11k_de64_tomo17_21_lim30_16bit.tif"  # Input data path, tif/h5 format
  output: "/gpfs/radev/project/kuan/zz545/251021_test"    # Output data path, precomputed format

input_format: "tif"                 # Input format "tif" or "h5"
h5:                                 # If input format is h5
  datasets: ["vol0",]               # Dataset of h5
roi: null                           # Select the RoI of iuput data: [x, y, w, h], default if null (all)
prec_info:                          # Output: precomputed data info
  lazy: false                       # Lazy load mode to save memeory
  num_channels: 1                   # Number of output channel
  layer_type: "image"               # Data Tpye: 'image' or 'segmentation'
  data_type: "uint16"               # Can pick any popular uint
  encoding: "raw"                   # Other options: 'jpeg', 'compressed_segmentation' (req. uint32 or uint64)
  resolution: [1.4, 1.4, 1.4]       # X,Y,Z values in nanometers
  voxel_offset: [0, 0, 0]           # Values X,Y,Z values in voxels
  chunk_size: [64, 64, 64]          # Rechunk of image X,Y,Z in voxels
  compress: false                   # Compressed storage

hpc:                                # HPC submission cnfiguration
  enable: true                      # Enable switch
  scheduler: "slurm"                # "slurm" 
  job_dir: "kns/jobs/convert"      # Directory for generating scripts and lists
  python_bin: "python"              # Python path
  time: "00:30:00"                  # Time for each task
  cpus: 16                          # Cpu number 
  mem: "4G"                         # Mem per cpu
  partition: "day"                  # Partition
  extra_modules: ["StdEnv", ]                                         # List of modules requiring loading
  conda: "/gpfs/radev/home/zz545/miniconda3/etc/profile.d/conda.sh"   # Path of conda
  env: "pytc"                                                         # Name of conda env
  work_path: /gpfs/radev/home/zz545/project                           # Work Path

